### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by LSHO1224** [dgh06175/Java_study_2#1]
MVC 패턴 (Model-View-Controller)

Model: 애플리케이션의 데이터와 로직을 관리한다.
View: 사용자에게 보여지는 UI 부분을 관리한다.
Controller: 사용자의 입력을 처리하고 Model과 View 사이의 인터랙션을 조정한다.
클래스 다이어그램
Model 클래스

GameModel
Properties:
List<Integer> computerNumbers: 컴퓨터가 선택한 숫자 리스트
Methods:
generateRandomNumbers(): 1에서 9까지 서로 다른 임의의 수 3개를 선택한다.
evaluateGuess(List<Integer> guess): 사용자의 추측을 평가하고 결과를 반환한다.
View 클래스

GameView
Methods:
displayInstructions(): 게임의 지침을 표시한다.
showResult(String result): 추측의 결과를 표시한다.
askForGuess(): 사용자에게 추측을 입력하도록 요청한다.
showError(String message): 에러 메시지를 표시한다.
askToRestartOrExit(): 게임을 다시 시작할지 또는 종료할지 사용자에게 묻는다.
Controller 클래스

GameController
Properties:
GameModel model: 게임의 모델
GameView view: 게임의 뷰
Methods:
startGame(): 게임을 시작한다.
processUserGuess(List<Integer> guess): 사용자의 추측을 처리한다.
restartOrExit(): 게임을 다시 시작하거나 종료한다.

**Comment by dgh06175** [comment]
확인했습니다

**Comment by LSHO1224** [comment]
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;

// Model
class GameModel {
    private List<Integer> computerNumbers = new ArrayList<>();

    public GameModel() {
        generateRandomNumbers();
    }

    private void generateRandomNumbers() {
        for (int i = 1; i <= 9; i++) {
            computerNumbers.add(i);
        }
        Collections.shuffle(computerNumbers);
        computerNumbers = computerNumbers.subList(0, 3);
    }

    public String evaluateGuess(List<Integer> guess) {
        int strike = 0;
        int ball = 0;

        for (int i = 0; i < 3; i++) {
            if (guess.get(i).equals(computerNumbers.get(i))) {
                strike++;
            } else if (computerNumbers.contains(guess.get(i))) {
                ball++;
            }
        }

        if (strike == 0 && ball == 0) {
            return "낫싱";
        }
        return strike + "스트라이크 " + ball + "볼";
    }

    public boolean isCorrectGuess(List<Integer> guess) {
        return guess.equals(computerNumbers);
    }
}

// View
class GameView {
    private Scanner scanner = new Scanner(System.in);

    public void displayInstructions() {
        System.out.println("1부터 9까지의 서로 다른 숫자 3개를 맞춰보세요!");
    }

    public List<Integer> askForGuess() {
        System.out.println("숫자 3개를 입력하세요 (예: 123): ");
        String input = scanner.nextLine();
        List<Integer> guess = new ArrayList<>();
        for (char c : input.toCharArray()) {
            guess.add(Character.getNumericValue(c));
        }
        return guess;
    }

    public void showResult(String result) {
        System.out.println(result);
    }

    public void showError(String message) {
        System.out.println("오류: " + message);
    }

    public boolean askToRestartOrExit() {
        System.out.println("다시 시작하려면 'restart'를 입력하고, 종료하려면 아무 키나 누르세요.");
        String input = scanner.nextLine();
        return "restart".equalsIgnoreCase(input);
    }
}

// Controller
class GameController {
    private GameModel model;
    private GameView view;

    public GameController() {
        model = new GameModel();
        view = new GameView();
    }

    public void startGame() {
        view.displayInstructions();
        while (true) {
            List<Integer> guess = view.askForGuess();
            String result = model.evaluateGuess(guess);
            view.showResult(result);
            if (model.isCorrectGuess(guess)) {
                if (view.askToRestartOrExit()) {
                    model = new GameModel();
                    view.displayInstructions();
                } else {
                    break;
                }
            }
        }
    }
}

public class NumberBaseballGame {
    public static void main(String[] args) {
        GameController controller = new GameController();
        controller.startGame();
    }
}
